### ISSUE TITLE
Renovate is looking at wrong repo

### ISSUE THREAD

**Issue by bjw-s** [Doonga/vyos-config#1]
Hi! 👋 

I noticed you have copied my repo. Turns out that your Renovate config is still pointing towards mine, causing it to create issues  over there :(

https://github.com/Doonga/vyos-config/blob/main/.github/renovate.json5#L10

**Comment by Doonga** [comment]
Oh crap! Sorry! I'll fix that.

**Comment by Doonga** [comment]
Fixed!
